### ISSUE TITLE
Machine-readable output for vpnutil

### ISSUE THREAD

**Issue by Spaider** [Timac/VPNStatus#12]
It would be nice to have machine-readable output for `vpnutil`. JSON looks like obvious choice these days.

**Comment by Timac** [comment]
Sounds like a great idea for the `list` and `status` options for `vpnutil`

**Comment by Timac** [comment]
@Spaider `vpnutil list` now outputs such a json:

```
{
  "VPNs" : [
    {
      "name" : "VPN1",
      "status" : "Connected"
    },
    {
      "name" : "VPN2",
      "status" : "Disconnected"
    },
    {
      "name" : "VPN3",
      "status" : "Disconnected"
    }
  ]
}
```
