### ISSUE TITLE
Auto-connect based on SSID

### ISSUE THREAD

**Issue by javamon01** [Timac/VPNStatus#14]
Hi, this utility functions great as-is, but would it be possible to auto-connect only when outside of a given list of SSIDs?  I.e.: The utility would accept a comma separated list of SSIDS and only auto-connect when not connected to that list. 

I've found a few ways to do this on iOS through a vpn mobileconfig, but such a profile doesn't seem to work on the Mac.

Thanks!

**Comment by Timac** [comment]
@javamon01 This feature is now implemented thanks to @cliss . You can find the version 1.2 with precompiled binaries here: https://github.com/Timac/VPNStatus/releases/tag/1.2

**Comment by javamon01** [comment]
> @javamon01 This feature is now implemented thanks to @cliss . You can find the version 1.2 with precompiled binaries here: https://github.com/Timac/VPNStatus/releases/tag/1.2

Thank you both! I appreciate the time and effort to make this work.

**Comment by Olivier-Levasseur** [comment]
Hi, I've found out how to don't autoconnect VPN for specific Wi-Fi SSIDs, but what about when using LAN? 
Is it possible to don't auto-connect VPN when you connect your Mac to a specific LAN?
Because at home I usually use LAN connection and when I'm at home I don't need VPN to be active, since I use it only in remote (in Wifi).

**Comment by Timac** [comment]
> Hi, I've found out how to don't autoconnect VPN for specific Wi-Fi SSIDs, but what about when using LAN? Is it possible to don't auto-connect VPN when you connect your Mac to a specific LAN? Because at home I usually use LAN connection and when I'm at home I don't need VPN to be active, since I use it only in remote (in Wifi).

@Olivier-Levasseur VPNStatus can detect if you are connected via Ethernet or if you are on a specific IP address. However, that would be a new feature request to be tracked in a different ticket.

**Comment by Olivier-Levasseur** [comment]
So how can you tell to VPNStatus to don't autoconnect if you are using a specific ethernet connection? I want to exclude the home ethernet other than the wifi home connection

**Comment by Timac** [comment]
> So how can you tell to VPNStatus to don't autoconnect if you are using a specific ethernet connection? I want to exclude the home ethernet other than the wifi home connection

@Olivier-Levasseur This is possible but needs to be implemented. If I understand correctly, you want to detect when you are using Ethernet and it is on a specific external IP address?

**Comment by Olivier-Levasseur** [comment]
I basically need that VPNstatus doesn't autoconnect when I use ethernet of my home's internet line.
