### ISSUE TITLE
homebrew support 🍻 

### ISSUE THREAD

**Issue by MichaelSp** [Timac/VPNStatus#16]
Great tool! ❤️ 
Homebrew support would be a great addition to it 

https://docs.brew.sh/

**Comment by Timac** [comment]
Thanks @MichaelSp !

I almost never use Homebrew. I am not sure what would be required to build Homebrew support and maintain it in the future.

An alternative solution would be to subscribe to receive notifications when a new release is available. See https://github.com/Timac/VPNStatus/releases

**Comment by MichaelSp** [comment]
I'll try to submit a PR for that...

**Comment by MichaelSp** [comment]
I just read - it will probably be rejected because it's not "notable enough" 😿 

![image](https://user-images.githubusercontent.com/448282/155950216-7ef3d3d4-240d-4dc3-8545-1378acf8b722.png)

https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md#rejected-casks
https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md#exceptions-to-the-notability-threshold

**Comment by Gerst20051** [comment]
This can still be supported on `brew` if it's part of a tap.

https://docs.brew.sh/Taps
