### ISSUE TITLE
Changing menu bar icon

### ISSUE THREAD

**Issue by a-rock-lobster** [Timac/VPNStatus#18]
Hullo,

Thanks for sharing VPNStatus. 

I've been trying to locate where the app keeps the menu bar icons stored. I wanted to change them to something a bit more in keeping with the black and white menu bar theme, but as there aren't any image files in the typical places I haven't been able to. 

Perhaps someone could point me in the right direction?

Thanks again,

**Comment by Timac** [comment]
Hey @a-rock-lobster ,
Thanks for using VPNStatus!

The images are located in the Asset Catalog that you can find at https://github.com/Timac/VPNStatus/tree/master/VPNStatus/Assets.xcassets

For example you can find the green `On` icon at https://github.com/Timac/VPNStatus/blob/master/VPNStatus/Assets.xcassets/VPNStatusItemOnImage.imageset/VPNStatusItemOnImage%402x.png

If you want to change the icon, I would suggest to:

- clone the repository
- replace the images
- recompile VPNStatus using Xcode

Hope this helps,
Alexandre

**Comment by Timac** [comment]
@a-rock-lobster You can now set black and white menu bar images in the preferences window in VPNStatus 3.0: https://github.com/Timac/VPNStatus/releases
