### ISSUE TITLE
VPN Connection The server is unreachable VPN App Server Address Unknown

### ISSUE THREAD

**Issue by emarcelcom** [Timac/VPNStatus#19]
Connecting to L2TP VPN is working fine when connecting from macOS native network system preferences.
When using the VPNApp, VPNStatus app I can't connect since the app doesn't read server address.
<img width="409" alt="VPNApp 2022-07-18 12-19-23(1)" src="https://user-images.githubusercontent.com/31213069/179492263-58b5c880-548d-449d-98a4-bcac2abda93a.png">

MacOS: 12.4
VPNApp latest release.
![Monosnap 2022-07-18 12-27-20(2)](https://user-images.githubusercontent.com/31213069/179493332-fc2703d0-d903-49bc-a34d-a3ddd5c4c9b9.png)

**Comment by Timac** [comment]
Thanks for the bug report. I don't use L2TP here but if I create a fake L2TP VPN, the server address is visible in VPNStatus.
I think you will need to debug the code to see what is happening.

**Comment by emarcelcom** [comment]
Strange, after I recreated VPN connection it works fine. Though, there is still that removed connection on the list. This issue may be closed.
