### ISSUE TITLE
Defaults settings not being read

### ISSUE THREAD

**Issue by skaiteo** [Timac/VPNStatus#22]
I've followed the instructions on the README, and set up the settings as such:
![image](https://user-images.githubusercontent.com/32006116/207510532-5c0bff33-8041-4fd3-85f7-023042b255b2.png)
But it doesn't seem to be reading those values, as the auto connect still takes 120 seconds, and it still reconnects to VPN on those SSIDs.

I'm running a 2021 M1 MacBook Pro 16-inch. Is there perhaps some permission issue that's not allowing it to read those settings?

**Comment by Timac** [comment]
@skaiteo The preferences look correct. Are you using the latest version 1.2?
See https://github.com/Timac/VPNStatus/releases/tag/1.2

**Comment by skaiteo** [comment]
Yeap I am

**Comment by Timac** [comment]
@skaiteo I just checked: the minimum value for `AlwaysConnectedRetryDelay` is 11. If you set this value to 10 or lower, the default 120 seconds will be used. I will add a note in the README about it, sorry about that!

Let me know if this solves the issue

**Comment by skaiteo** [comment]
If I remember correctly, it wasn't working even with a larger value like 30, but I'll give that a try and report back.

**Comment by Timac** [comment]
I just tested it successfully with:

- macOS Ventura 13.0.1
- MacBook Pro 14" M1
- `AlwaysConnectedRetryDelay` set to 15

**Comment by skaiteo** [comment]
Alright, `AlwaysConnectedRetryDelay` works perfectly, but `IgnoredSSIDs` is still not working.

**Comment by Timac** [comment]
Thanks @skaiteo, there was indeed an issue where the preferences `IgnoredSSIDs` would be ignored if the VPN was set to always auto connect.

I fixed the issue and release the version 1.3. You can find it here: https://github.com/Timac/VPNStatus/releases

**Comment by skaiteo** [comment]
Thanks for the quick action, I've tested it, and it works perfectly now!

As a side note, I discovered that the IgnoredSSID settings doesn't require an app restart. It seems to read the setting every time the timer fires.
