### ISSUE TITLE
Is there a way to configure vpnutil to ignore some of the VPNs?

### ISSUE THREAD

**Issue by skoch13** [Timac/VPNStatus#25]
Thank you for these beautiful tool!

I tried the suggested option `defaults write org.timac.VPNStatus IgnoredVPNs "Little Snitch,HiddenVPN,AnotherHiddenVPN"`, but I guess it works only for the VPNStatus app, while I'm solely using the cli one.

So the question is there a way to hide some of the VPNs from the list?

**Comment by Timac** [comment]
The command line tool `vpnutil` has no embedded info.plist. As such it has no BundleID and can't load the preferences that you could set using:
```
defaults write org.timac.vpnutil IgnoredVPNs "Little Snitch,HiddenVPN,AnotherHiddenVPN"
```

The right solution would be to embed an Info.plist as I documented for other command line tools here: https://blog.timac.org/2021/0516-mac-app-store-embedding-a-command-line-tool-using-paths-as-arguments/#infoplist

**Comment by Timac** [comment]
@skoch13 I added the embedded Info.plist. If you recompile the command line tool vpnutil, you should now be able to hide the VPNs using:

```
defaults write org.timac.vpnutil IgnoredVPNs "Little Snitch,HiddenVPN,AnotherHiddenVPN"
```

**Comment by skoch13** [comment]
@Timac wow! thank you!
