### ISSUE TITLE
vpnutil: Update 'usage' to mention 'list' option

### ISSUE THREAD

**Issue by Tormen** [Timac/VPNStatus#26]
Ability to list all VPNs and their status: Minimum: Name of VPN (as needed for `start` and `stop` command, as well as status of VPN (I imagine the possibilities would be: connected, disconnected, connecting, ...).

Make this feature accessible via a 3rd command parameter (instead of start/stop): Something like `list`.

Output format: I don't really mind. The possibilities I see:
* Maybe output in TABLE format using TAB as separator.
* Or output in RECORD format.
* Or as suggested in JSON format.

This would really be useful.
Especially as the MacOS built-in tools don't seem to be able :/

Please let me know what would be needed in terms of financial sponsoring for this item. Thanks a lot in advance!

**Comment by Timac** [comment]
Hey @Tormen ,

The `vpnutil` command line tool already supports a `list` parameter. When running the command `vpnutil list`, you will see an output like:

```
VPN1 Connected
VPN2 Disconnected
VPN3 Disconnected
```

where `VPN1`, `VPN2` and `VPN3` are the names of the VPNs.

I assume that you would prefer to get a JSON output format like:

```
{
  "VPN1": {
    "status": "Connected"
  },
  "VPN2": {
    "status": "Disconnected"
  },
  "VPN3": {
    "status": "Disconnected"
  }
}
```

Would this JSON work for you? Is there anything missing in this output that you would like to see?

**Comment by Tormen** [comment]
Hi @Timac , 

The output of the `list` parameter could be improved 
by using a "TAB" character, instead of "SPACE" 
to separate the NAME of the VPN and the status, 
as the VPN NAME /can/ also contain spaces.

Tormen

**Comment by Timac** [comment]
@Tormen Thanks again for the great suggestions. I implemented 2 changes:

- The usage now mentions the `list` parameter
- `vpnutil list` now outputs a json format. This issue was also tracked by https://github.com/Timac/VPNStatus/issues/12 . If you run `vpnutil list`, you should now see a json like this:

```
{
  "VPNs" : [
    {
      "name" : "VPN1",
      "status" : "Connected"
    },
    {
      "name" : "VPN2",
      "status" : "Disconnected"
    },
    {
      "name" : "VPN3",
      "status" : "Disconnected"
    }
  ]
}
```
