### ISSUE TITLE
IgnoredSSIDs doesn't work anymore after upgrading to macOS Sonoma

### ISSUE THREAD

**Issue by telephono** [Timac/VPNStatus#28]
I am using VPNStatus version 1.4 with following config:
```
defaults read org.timac.VPNStatus
{
   ---snip---

    IgnoredSSIDs = "FRITZ!Box 7580 XX";

   ---snip---
}
```

Everything worked beautyfully until I upgraded to macOS Sonoma. After that, the wifi isn't ignored anymore and VPNStatus always tries to connect to the VPN even when connected to the FRITZ!Box 7580 XX wifi.

**Comment by telephono** [comment]
Following your advice from issue #24 https://github.com/Timac/VPNStatus/blob/8fe60978d8647caaecd2f26462200f07819ba96e/Common/ACConnectionManager.m#L233

I tried
```objective-c
CWInterface *wifi = [[CWWiFiClient sharedWiFiClient] interface];
printf("%s", [wifi.ssid UTF8String]);
```

But this only returns `(null)`...

**Comment by telephono** [comment]
I found this thread: [Developer Forums](https://developer.apple.com/forums/thread/732431)
Apperently you have to enable Location Services to get acces to the SSID in Sonoma.

**Comment by Timac** [comment]
Thanks a lot @telephono for the bug report and info! Once I update to Sonoma (in a couple of days probably), I will try to address this issue.

**Comment by Timac** [comment]
macOS 14 Sonoma support has been added in VPNStatus 2.0: [https://github.com/Timac/VPNStatus/releases](https://github.com/Timac/VPNStatus/releases)

The precompiled binaries are also now code-signed to simplify the installation.
