### ISSUE TITLE
It will be great to see your tools in brew

### ISSUE THREAD

**Issue by valdemar1977** [Timac/VPNStatus#30]
It will be great to see your tools in brew!!!

**Comment by Timac** [comment]
@valdemar1977 Would you want the command line tool `vpnutil` or the GUI app `VPNStatus` in brew?
I never submitted myself a Cask so I would be more than happy to learn about your suggestions here

**Comment by valdemar1977** [comment]
I'm using vpnutil

**Comment by dronenb** [comment]
I was considering writing both a cask and a formula for these. @Timac I am happy to submit a PR to upstream `brew` but would also be happy to submit a PR to your own `homebrew-tap` repository if you're interested in creating one yourself...

**Comment by Timac** [comment]
@dronenb I created a `homebrew-tap` repository at https://github.com/Timac/homebrew-vpnstatus/

**Comment by dronenb** [comment]
This issue can be closed as this is now available:

```
brew tap timac/vpnstatus
brew install timac/vpnstatus/vpnutil
brew install --cask timac/vpnstatus/vpnstatus
```

**Comment by Timac** [comment]
Thanks a lot @dronenb . I updated the README to mention homebrew.
