### ISSUE TITLE
Not starting after upgrade to macos 14.4

### ISSUE THREAD

**Issue by wohnout** [Timac/VPNStatus#33]
Hi,
I made a huge mistake and upgraded to 14.4 too soon. One of the issues I have after the upgrade is that VPNStatus doesn't autostart.

**Comment by Timac** [comment]
@wohnout Could you please provide more details about what you mean by VPNStatus not autostarting?

Do you mean that the app itself is not launched when you turn on your computer? If this is the case, that sounds more like a problem with your macOS installation. You should check System Settings > General > Login Items

**Comment by wohnout** [comment]
Ok. VPNStatus was not present there, but it was working before ... no idea what happened
