### ISSUE TITLE
compatible with sonoma 14? 

### ISSUE THREAD

**Issue by halukkaramete** [Timac/VPNStatus#36]
My VPN connection ( to Azure ) keeps dropping while I do VSCODE and Transmit.  I'd like to be able to be notified immediately (thru some sound or some sort of a visual notification ) that the VPN is disconnected. This would then prevent me to do a very common COMMAND-S (on the current file ) which automatically triggers the FTP upload of the file I'm working in the VS Code.  It then takes a ton of effort to tell Transmit to cancel that upload, even leading to the quitting transmit.  Since the VPN drops too often, and since I save files back to server 100s of times a day, this does become a problem. 

Does your tool solve this problem and pop an alert that VPN is dropped?

**Comment by Timac** [comment]
@halukkaramete VPNStatus displays a different icon in the menu bar depending on whether the VPN is connected or not. It doesn't play a sound or display a notification if the VPN connection drops.

But in your case, it seems that you want to use the `Always Auto Connect` feature of VPNStatus to ensure that you are always connected to the VPN.

![VPNStatusAutoConnect](https://github.com/Timac/VPNStatus/assets/738543/1d96ca46-57a6-46e5-9b37-b8da20d1440d)
