### ISSUE TITLE
Release the new version to apply changes in PR #1

### ISSUE THREAD

**Issue by trung-huynh** [Timac/VPNStatus#5]
PR: https://github.com/Timac/VPNStatus/pull/1 added the great features to fetch all VPNs as well as the status of specified one, better to release the new version to apply those changes. The original version from blog is out dated.

**Comment by trung-huynh** [comment]
@Timac, it would be nice if you can release the new features.

**Comment by Timac** [comment]
@trung-huynh Sorry for the long delay. Please find the latest precompiled binaries here: https://github.com/Timac/VPNStatus/releases/tag/1.0
