### ISSUE TITLE
Feature Request: set delay for auto-reconnect

### ISSUE THREAD

**Issue by whowantsmybigdata** [Timac/VPNStatus#8]
Hi,
thanks for your program, before I used a self-written skript to auto-reconnect via IPSec but this here became really essential when switched to IKeV2!
When the Mac is suspended (I have an old 2008 one running Catalina via the patcher, so no hibernation) it looses the connection to VPN, which is normal and fine.
Thing is when waking it up again, the time VPNStatus needs to autoconnect is set for that long (didnt measure it exactly) I end up connecting manually all the time which is not a major drawback but would be a nice feature beeing able to set this delay however its needed. E.g. I would check every 10sec or so as I guess its just checking the IKeV2 interface locally and not checking if its possible to reach the VPN, so it would only use a bit more memory and power, right?!).
Thanks in advance!

**Comment by Timac** [comment]
Hi,

Great to hear you like VPNStatus!

VPNStatus tries to reconnect to the VPN every 120s by default. There is however a secret preference to change this value. For example to set to 30s, you should quit VPNStatus and run this command line in a Terminal window:

```
defaults write org.timac.VPNStatus AlwaysConnectedRetryDelay -int 30
```

After you relaunch VPNStatus, it should try to reconnect every 30s.
I believe that you are looking for this preference.

Hope this help,
Alexandre

**Comment by whowantsmybigdata** [comment]
great exactly what I was looking for - thanks a lot!!
