### ISSUE TITLE
duplicate VPN connection

### ISSUE THREAD

**Issue by Potato-007** [Timac/VPNStatus#9]
in Apple / System Preferences / Network pref.pane I have 2 locations and within each there's the same VPN connection - this is fine. But in VPNStatus I see many possible VPN connections, these seams to be previous settings I used for testing that are already deleted days ago and should not exits anymore. I have an impression that the Network pref.pane and the VPNStatatus are not pooling network setting infos from the same place.

![Screen Shot 2021-01-29 at 10 00 31](https://user-images.githubusercontent.com/62175671/106254581-2aff2200-6219-11eb-8d53-43c99ce42700.png)
![Screen Shot 2021-01-29 at 9 34 55](https://user-images.githubusercontent.com/62175671/106254592-2d617c00-6219-11eb-9094-41bb0b3a4238.png)

**Comment by Timac** [comment]
Thanks for the bug report!

VPNStatus loads the list of VPNs using the private API `loadConfigurationsWithCompletionQueue:handler:` from the NetworkExtension framework. It could be a bug in Apple's code or just some unsupported edge cases by using this private API.

I am wondering:

- Do you see the same duplicated list with the official 'VPN Status' status item from Apple in the menubar?
- If you quit and relaunch VPNStatus, do you still have duplicated VPNs?
- Did you try to reboot your computer to make sure that the NetworkExtension is not in some weird state?

I would love to hear more about this to see if I can do anything.

**Comment by Potato-007** [comment]
No > "Do you see the same duplicated list with the official 'VPN Status' status item from Apple in the menubar?"
Yes > "If you quit and relaunch VPNStatus, do you still have duplicated VPNs?"
Yes > "Did you try to reboot your computer to make sure that the NetworkExtension is not in some weird state?"

what I tried now is that I deleted one of the 2 locations I had, then restarted VPNStatus, but old deleted VPN settings still appear in the list

**Comment by akiltopu** [comment]
exactly same problem on Big Sur 11.4 :(

**Comment by shlyakpavel** [comment]
I'm facing the same issue

**Comment by Potato-007** [comment]
here's how I fixed it:

1) boot into Recovery Mode with CMD + R
2) run the following command with Terminal:
rm -rf com.apple.networkextension.plist

reboot

note: this will delete all the settings related to Network and VPN

**Comment by Timac** [comment]
Thanks a lot @Potato-007 for sharing your solution. It definitively seems like some caches from Apple are not cleaned up when removing the VPNs.

**Comment by shlyakpavel** [comment]
> Thanks a lot @Potato-007 for sharing your solution. It definitively seems like some caches from Apple are not cleaned up when removing the VPNs.

It's not a complete solution imo
1. It looses all the network data (that is bad)
2. It requires to disable system integrity protection on m1 that disables some features such as iOS apps

In fact, I'm able to manually edit this file to remove networks I don't need, but now I don't know a way to edit this file without disabling integrity protection

**Comment by Timac** [comment]
@shlyakpavel Sadly I guess that only Apple would be able to properly address this issue. I would recommend to submit a bug to Apple at https://feedbackassistant.apple.com

**Comment by Olivier-Levasseur** [comment]
hi, is there something we can do to delete old VPNs in the list of VPNStatus?

**Comment by Timac** [comment]
> hi, is there something we can do to delete old VPNs in the list of VPNStatus?

VPNStatus uses the VPN list provided by macOS. You can delete old VPNs using System Settings > VPN

**Comment by Olivier-Levasseur** [comment]
the problem is that I still see old VPN that now are no longer present in System Settings.

**Comment by Olivier-Levasseur** [comment]
ah ok, I just found out that in the options of VPNstatus, under the section called "ignored", you can specify which old VPN to hide. cheers to the developer ;)
